baseURL = 'https://Wanner987.github.io'
languageCode = 'en-us'
title = 'music api documentation and portfolio for ASE 230 '
theme = 'ananke'

[params]
  author = "Tanner Andrews"
  description = "api documentation and portfolio"
  github = "https://github.com/yourusername"
  linkedin = "https://linkedin.com/in/yourusername"
  email = "john@example.com"

[pagination]
  pagersize = 5

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects" 
    url = "/projects/"
    weight = 2
